
version: "3"
services:
  node:
    image: "node:current-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"


# You can then run using Docker Compose:
# $ docker-compose up -d

